# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_base'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_base'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
vars:
  tblRecordCounts_location: "`rand-rusaweb.sbxx_russell_magidson_BI_Logs.tblRecordCounts`"

models:
  dbt_base:
    +materialized: table
    +database: |
      {%- if target.name == "sbx_target" -%} us-atlstg-dev-11c7
      {%- elif target.name == "tst_target" -%} us-atlstg-dev-11c7
      {%- elif target.name == "acc_target" -%} us-atlstg-qa-cd80
      {%- elif target.name == "prd_target" -%} us-atlstg-prd-55a8
      {%- else -%} us-atlstg-dev-11c7
      {%- endif -%}
    BackOffice_DeDup:
      +tags: "BackOffice_DeDup"
      02_stg:
        +schema: staging_BackOffice_DeDup # Our custom schema
        +tags: 
          - "stg"
          - "staging"
      03_dwh:
        +schema: data_warehouse_BackOffice_DeDup # Our custom schema
        +tags: 
          - "dwh"
          - "data_warehouse"
        +materialized: incremental
      04_dm:
        +schema: data_mart_BackOffice_DeDup # Our custom schema
        +tags: 
          - "dm"
          - "data_mart"

    BI_BO:
      +tags: "BackOffice_BI_BO"
      02_stg:
        +schema: staging_BO_BI # Our custom schema
        +tags: 
          - "stg"
          - "staging"
      03_dwh:
        +schema: data_warehouse_BO_BI # Our custom schema
        +tags: 
          - "dwh"
          - "data_warehouse"
        +materialized: incremental
      04_dm:
        +schema: data_mart_BO_BI # Our custom schema
        +tags: 
          - "dm"
          - "data_mart"

    BackOffice_DeDup_Logs:
      +schema: BI_Logs
      +tags: 
        - "logs"
        - "BI_BackOffice_Logs"

    BI_BO_Logs:
      +schema: BI_Logs
      +tags: 
        - "logs"
        - "BI_BO_Logs"

      # 04_dm_front:
      #   +database: |
      #     {%- if target.name == "prd_target"  -%} datalake-frontoffice
      #     {%- elif target.name == "acc_target"  -%} us-datalakefo-qa-a298
      #     {%- else -%} us-atldm-test-dev-9198
      #     {%- endif -%}
    # bc_case_template:
    #   02_stg:
    #     +database: |
    #       {%- if target.name == "prd_target" -%} us-atlstg-prd-55a8
    #       {%- elif target.name == "acc_target" -%} us-atlstg-qa-cd80
    #       {%- else -%} us-atlstg-dev-11c7
    #       {%- endif -%}
    #   03_dwh:
    #     +database: |
    #       {%- if target.name == "prd_target" -%} us-atldwh-prd-60df
    #       {%- elif target.name == "acc_target" -%} us-atldwh-qa-e9af
    #       {%- else -%} us-atldwh-dev-1165
    #       {%- endif -%}
    #   04_dm:
    #     +database: |
    #       {%- if target.name == "prd_target"  -%} us-atldm-test-prd-99b5
    #       {%- elif target.name == "acc_target"  -%} us-atldm-test-qa-2114
    #       {%- else -%} us-atldm-test-dev-9198
    #       {%- endif -%}
    #   04_dm_front:
    #     +database: |
    #       {%- if target.name == "prd_target"  -%} datalake-frontoffice
    #       {%- elif target.name == "acc_target"  -%} us-datalakefo-qa-a298
    #       {%- else -%} us-atldm-test-dev-9198
    #       {%- endif -%}
