# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_base'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_base'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  dbt_base:
    # +dataset: base
    +materialized: table
    BackOffice_DeDup:
      02_stg:
        +schema: staging_BI_BO
        +database: |
          {%- if target.name == "prd_target" -%} us-atlstg-prd-55a8
          {%- elif target.name == "acc_target" -%} us-atlstg-qa-cd80
          {%- else -%} us-atlstg-dev-11c7
          {%- endif -%}
      03_dwh:
        +schema: data_warehouse_BI_BO
        +materialized: incremental
        +database: |
          {%- if target.name == "prd_target" -%} us-atldwh-prd-60df
          {%- elif target.name == "acc_target" -%} us-atldwh-qa-e9af
          {%- else -%} us-atldwh-dev-1165
          {%- endif -%}
      04_dm:
        +schema: data_mart_BI_BO
        +database: |
          {%- if target.name == "prd_target"  -%} us-atldm-test-prd-99b5
          {%- elif target.name == "acc_target"  -%} us-atldm-test-qa-2114
          {%- else -%} us-atldm-test-dev-9198
          {%- endif -%}
      # 04_dm_front:
      #   +database: |
      #     {%- if target.name == "prd_target"  -%} datalake-frontoffice
      #     {%- elif target.name == "acc_target"  -%} us-datalakefo-qa-a298
      #     {%- else -%} us-atldm-test-dev-9198
      #     {%- endif -%}
    # bc_case_template:
    #   02_stg:
    #     +database: |
    #       {%- if target.name == "prd_target" -%} us-atlstg-prd-55a8
    #       {%- elif target.name == "acc_target" -%} us-atlstg-qa-cd80
    #       {%- else -%} us-atlstg-dev-11c7
    #       {%- endif -%}
    #   03_dwh:
    #     +database: |
    #       {%- if target.name == "prd_target" -%} us-atldwh-prd-60df
    #       {%- elif target.name == "acc_target" -%} us-atldwh-qa-e9af
    #       {%- else -%} us-atldwh-dev-1165
    #       {%- endif -%}
    #   04_dm:
    #     +database: |
    #       {%- if target.name == "prd_target"  -%} us-atldm-test-prd-99b5
    #       {%- elif target.name == "acc_target"  -%} us-atldm-test-qa-2114
    #       {%- else -%} us-atldm-test-dev-9198
    #       {%- endif -%}
    #   04_dm_front:
    #     +database: |
    #       {%- if target.name == "prd_target"  -%} datalake-frontoffice
    #       {%- elif target.name == "acc_target"  -%} us-datalakefo-qa-a298
    #       {%- else -%} us-atldm-test-dev-9198
    #       {%- endif -%}
