# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'bi_backoffice'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_base'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"


vars:
  # RAW - 00 Historic Datalake: Source
  # dataset_raw_prd: us-atlantaraw-prd-a628
  # dataset_raw_acc: us-atlantaraw-acc-36f2
  # dataset_raw_tst: us-atlantaraw-tst-013f
  # dataset_raw_dev: us-atlantaraw-dev-2fb8
  rand_rusaweb_dev: rand-rusaweb
  rand_rusaweb_tst: rand-rusaweb
  rand_rusaweb_acc: us-ergbq-qa-e523
  rand_rusaweb_prd: us-ergbq-prd-3693
  datalake_frontoffice_dev: us-datalakefo-qa-a298
  datalake_frontoffice_tst: datalake-frontoffice
  datalake_frontoffice_acc: datalake-frontoffice
  datalake_frontoffice_prd: datalake-frontoffice
  datalake_frontoffice_qa: us-ergbq-qa-e523
  dataset_raw_prd: us-atldm-test-prd-99b5
  dataset_raw_acc: us-atldm-test-qa-2114
  dataset_raw_tst: us-atldm-test-dev-9198
  dataset_raw_dev: us-atldm-test-dev-9198

  # DL - 01 Historic Datalake: Source
  # dataset_dl_prd: us-atlantadl-prd-b32c
  # dataset_dl_acc: us-atlantadl-acc-170d
  # dataset_dl_tst: us-atlantadl-tst-3c82
  # dataset_dl_dev: us-atlantadl-dev-eb95
  
  # STG - 02 Staging: Last Version of Data and Cleanings
  dataset_stg_prd: us-atlstg-prd-55a8
  dataset_stg_acc: us-atlstg-qa-cd80
  dataset_stg_tst: us-atlstg-dev-11c7
  dataset_stg_dev: us-atlstg-dev-11c7

  # DWH - 03 Data Warehouse: Dimensions and Facts
  dataset_dwh_prd: us-atldwh-prd-60df
  dataset_dwh_acc: us-atldwh-qa-e9af
  dataset_dwh_tst: us-atldwh-dev-1165
  dataset_dwh_dev: us-atldwh-dev-1165

  # DM - 04 Data marts ready for user or BI consumptions
  dataset_dm_prd: us-atldm-test-prd-99b5
  dataset_dm_acc: us-atldm-test-qa-2114
  dataset_dm_tst: us-atldm-test-dev-9198
  dataset_dm_dev: us-atldm-test-dev-9198

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  +materialized: table
  +on_schema_change: "sync_all_columns"
  dbt_base:
    +dataset: base
    # Config indicated by + and applies to all files under models/example/
    00_raw:
      +database: |
        {%- if target.name == "prd_target" -%} us-atldm-test-prd-99b5
        {%- elif target.name == "acc_target" -%} us-atldm-test-qa-2114
        {%- elif target.name == "tst_target" -%} us-atldm-test-dev-9198
        {%- else -%}  us-atldm-test-dev-9198
        {%- endif -%}
    01_dl:
      +database: |
        {%- if target.name == "prd_target" -%} us-atldwh-prd-60df
        {%- elif target.name == "acc_target" -%} us-atldwh-qa-e9af
        {%- elif target.name == "tst_target" -%} us-atldwh-dev-1165
        {%- else -%} us-atldwh-dev-1165
        {%- endif -%}
    02_stg:
      +database: |
        {%- if target.name == "prd_target" -%} us-atlstg-prd-55a8
        {%- elif target.name == "acc_target" -%} us-atlstg-qa-cd80
        {%- elif target.name == "tst_target" -%} us-atlstg-dev-11c7
        {%- else -%} us-atlstg-dev-11c7
        {%- endif -%}
    03_dwh:
      +materialized: incremental
      +database: |
        {%- if target.name == "prd_target" -%} us-atldwh-prd-60df
        {%- elif target.name == "acc_target" -%} us-atldwh-qa-e9af
        {%- elif target.name == "tst_target" -%} us-atldwh-dev-1165
        {%- else -%} us-atldwh-dev-1165
        {%- endif -%}
    04_dm:
      +database: |
        {%- if target.name == "prd_target"  -%} us-atldm-test-prd-99b5
        {%- elif target.name == "acc_target"  -%} us-atldm-test-qa-2114
        {%- elif target.name == "tst_target" -%} us-atldm-test-dev-9198
        {%- else -%} us-atldm-test-dev-9198
        {%- endif -%}