#Profiles configuration.
dbt_base:
  target: sbx_target
  outputs:
    sbx_target:
      dataset: "sbxx_{{ env_var('USER', 'unknown') | lower | trim }}"
      fixed_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: us-atlstg-dev-11c7
      #us-atldm-test-dev-9198
      #us-atlantadbt-dev-94e0
      threads: 3
      timeout_seconds: 600
      type: bigquery
    tst_target:
      dataset: "tstt_{{ env_var('USER', 'unknown') | lower | trim }}"
      fixed_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: us-atlstg-dev-11c7 #us-atlantadbt-dev-94e0
      threads: 3
      timeout_seconds: 600
      type: bigquery
    acc_target:
      dataset: acc
      fixed_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: us-atlstg-dev-11c7 #us-atlantadbt-dev-94e0
      threads: 3
      timeout_seconds: 600
      type: bigquery
    prd_target:
      dataset: prd
      fixed_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: us-atlstg-dev-11c7 #us-atlantadbt-prd-1ad0
      threads: 3
      timeout_seconds: 600
      type: bigquery
