{{ config(
    tags = ["ps_bi_line"], 
    alias = 'ps_bi_line'
    )
}}

SELECT
        bil.business_unit
        ,bil.invoice
        ,bil.line_seq_num
        ,bil.invoice_line
        ,bil.original_invoice
        ,bil.original_line_seq
        ,bil.next_adj_invoice
        ,bil.next_adj_line_seq
        ,bil.prior_adj_invoice
        ,bil.prior_adj_line_seq
        ,bil.latest_invoice
        ,bil.latest_line_seq
        ,bil.bill_source_id
        ,bil.subcust_qual1
        ,bil.subcust_qual2
        ,bil.adj_line_type
        ,bil.adjusted_flag
        ,bil.line_type
        ,bil.bi_currency_cd
        ,bil.base_currency
        ,bil.currency_cd_xeu
        ,bil.rt_effdt
        ,bil.charge_from_dt
        ,bil.charge_to_dt
        ,bil.identifier
        ,bil.descr
        ,bil.unit_of_measure
        ,bil.qty
        ,bil.orig_qty
        ,bil.unit_amt
        ,bil.price_recalc_flg
        ,bil.tax_cd
        ,bil.tax_exempt_cert
        ,bil.tax_exempt_flg
        ,bil.gross_extended_amt
        ,bil.net_extended_amt
        ,bil.orig_amount
        ,bil.gross_extended_bse
        ,bil.net_extended_bse
        ,bil.gross_extended_xeu
        ,bil.net_extended_xeu
        ,bil.tax_amt
        ,bil.tax_amt_bse
        ,bil.tax_amt_xeu
        ,bil.tax_pct
        ,bil.final_tax_flg
        ,bil.max_tax_flg
        ,bil.bi_tax_timing
        ,bil.vat_basis_amt
        ,bil.vat_basis_amt_bse
        ,bil.vat_basis_amt_xeu
        ,bil.vat_amt
        ,bil.vat_amt_bse
        ,bil.vat_amt_xeu
        ,bil.vat_trans_amt
        ,bil.vat_trans_amt_bse
        ,bil.vat_txn_type_cd
        ,bil.tax_cd_vat
        ,bil.tax_cd_vat_pct
        ,bil.vat_applicability
        ,bil.prod_grp_setid
        ,bil.vat_product_group
        ,bil.product_kit_id
        ,bil.vat_distrib_status
        ,bil.tax_vat_flg
        ,bil.rev_recog_basis
        ,bil.deferred_status
        ,bil.accrue_dt
        ,bil.tot_line_dst_pct
        ,bil.tot_line_dfr_pct
        ,bil.tot_line_uar_pct
        ,bil.tot_line_dst_amt
        ,bil.tot_line_dfr_amt
        ,bil.tot_line_uar_amt
        ,bil.tot_line_dst_bse
        ,bil.tot_line_dfr_bse
        ,bil.tot_line_uar_bse
        ,bil.tot_line_dst_xeu
        ,bil.tot_line_dfr_xeu
        ,bil.tot_line_uar_xeu
        ,bil.tot_discount_amt
        ,bil.tot_surcharge_amt
        ,bil.tot_discount_bse
        ,bil.tot_surcharge_bse
        ,bil.tot_discount_xeu
        ,bil.tot_surcharge_xeu
        ,bil.line_dst_seq_num
        ,bil.line_dfr_seq_num
        ,bil.line_uar_seq_num
        ,bil.last_note_seq_num
        ,bil.entry_type
        ,bil.entry_reason
        ,bil.pc_distrib_status
        ,bil.po_ref
        ,bil.po_line
        ,bil.business_unit_ca
        ,bil.contract_num
        ,bil.contract_dt
        ,bil.contract_type
        ,bil.bill_plan_id
        ,bil.bplan_ln_nbr
        ,bil.event_occurrence
        ,bil.xref_seq_num
        ,bil.contract_ppd_seq
        ,bil.business_unit_om
        ,bil.order_no
        ,bil.order_date
        ,bil.order_int_line_no
        ,bil.sched_line_nbr
        ,bil.business_unit_rma
        ,bil.rma_id
        ,bil.rma_line_nbr
        ,bil.product_id
        ,bil.dist_cfg_flag
        ,bil.freight_terms
        ,bil.bill_of_lading
        ,bil.ship_to_cust_id
        ,bil.ship_to_addr_num
        ,bil.ship_id
        ,bil.ship_type_id
        ,bil.ship_from_bu
        ,bil.ship_date
        ,bil.ship_time
        ,bil.sequence_nbr
        ,bil.sold_to_cust_id
        ,bil.sold_to_addr_num
        ,bil.resource_id
        ,bil.activity_type
        ,bil.system_source
        ,bil.emplid
        ,bil.ssn
        ,bil.empl_rcd
        ,bil.service_cust_id
        ,bil.service_addr_num
        ,bil.start_dt
        ,bil.end_dt
        ,bil.accumulate
        ,bil.error_status_bi
        ,bil.contract_line_num
        ,bil.business_unit_to
        ,bil.ist_txn_flg
        ,bil.ist_distrib_status
        ,bil.inventory_item
        ,bil.fiscal_regime
        ,bil.nature_of_txn1
        ,bil.nature_of_txn2
        ,bil.identifier_tbl
        ,bil.packslip_no
        ,bil.defer_dt
        ,bil.pprc_promo_cd
        ,bil.merch_type
        ,bil.list_price
        ,bil.entry_event
        ,bil.physical_nature
        ,bil.vat_treatment
        ,bil.vat_svc_supply_flg
        ,bil.vat_service_type
        ,bil.vat_dst_acct_type
        ,bil.vat_advpay_flg
        ,bil.voucher_style
        ,bil.country_loc_buyer
        ,bil.state_loc_buyer
        ,bil.country_loc_seller
        ,bil.state_loc_seller
        ,bil.country_vat_supply
        ,bil.state_vat_supply
        ,bil.country_vat_perfrm
        ,bil.state_vat_perfrm
        ,bil.state_ship_to
        ,bil.state_ship_from
        ,bil.exd_cust_catg_cd
        ,bil.stx_cust_catg_cd
        ,bil.vat_dflt_done_flg
        ,bil.inv_item_id
        ,bil.qty_base
        ,bil.exd_invoice_no
        ,bil.exd_invoice_line
        ,bil.org_setid
        ,bil.org_code
        ,bil.org_tax_loc_cd
        ,bil.exd_appl_flg
        ,bil.stx_appl_flg
        ,bil.exs_dflts_applied
        ,bil.exs_tax_txn_type
        ,bil.stx_tax_auth_cd
        ,bil.country_ship_to
        ,bil.country_ship_from
        ,bil.exd_itm_catg_cd
        ,bil.stx_itm_catg_cd
        ,bil.exs_serv_tax_flg
        ,bil.stx_form_cd
        ,bil.form_distrib_stat
        ,bil.exd_assess_value
        ,bil.exd_uom
        ,bil.exd_conversion_rt
        ,bil.exd_use_av_flg
        ,bil.exd_tax_rate_cd
        ,bil.exd_tax_rate_src
        ,bil.exd_tax_amt
        ,bil.exd_tax_amt_bse
        ,bil.exd_tax_amt_rpt
        ,bil.stx_tax_rate_cd
        ,bil.stx_tax_rate_src
        ,bil.stx_tax_amt
        ,bil.stx_tax_amt_bse
        ,bil.stx_tax_amt_rpt
        ,bil.exs_currency_rptg
        ,bil.business_unit_amto
        ,bil.asset_id
        ,bil.profile_id
        ,bil.cost_type
        ,bil.country_vat_billfr
        ,bil.country_vat_billto
        ,bil.state_vat_default
        ,bil.lang_descr_ovr
        ,bil.so_id
        ,bil.business_unit_rf
        ,bil.source_ref_type
        ,bil.source_ref_no
        ,bil.source_ref_key
        ,bil.ca_pgp_seq
        ,bil.sum_template_id
        ,bil.sum_group_type
        ,bil.sum_group_id
        ,bil.cust_deposit_id
        ,bil.business_unit_pc
        ,bil.project_id
        ,bil.activity_id
        ,bil.resource_type
        ,bil.resource_category
        ,bil.resource_sub_cat
        ,bil.analysis_type
        ,bil.user_amt1
        ,bil.user_amt2
        ,bil.user_amt1_bse
        ,bil.user_amt2_bse
        ,bil.user_amt1_xeu
        ,bil.user_amt2_xeu
        ,bil.user_dt1
        ,bil.user_dt2
        ,bil.user1
        ,bil.user2
        ,bil.user3
        ,bil.user4
        ,bil.user5
        ,bil.user6
        ,bil.user7
        ,bil.user8
        ,bil.user9
        ,bil.process_instance
        ,bil.add_dttm
        ,bil.last_update_dttm
        ,bil.last_maint_oprid
        ,bil.ofac_status
        ,bil.sdn_publish_date
        ,bil.fss_activity_dt
        ,bil.fss_user_ovr
        ,bil.customer_po_line
        ,bil.customer_po_sched
        ,bil.pc_cf_change_flg
        ,bil.credit_reason
        ,bil.vat_rvrse_chg_gds
        ,bil.tax_cd_vat_rvc
        ,bil.tax_cd_vat_rvc_pct
        ,bil.vat_amt_rvc
        ,bil.vat_amt_rvc_bse
        ,bil.vat_amt_rvc_xeu
        ,bil.temp_invoice
        ,bil.insert_datetime as source_insert_datetime

FROM {{ source( 'datalake-frontoffice-fs_bo', 'PS_BI_HDR')}} as bih

JOIN {{ source( 'datalake-frontoffice-fs_bo', 'PS_BI_LINE')}} as bil
    ON bih.business_unit = bil.business_unit 
    AND bih.invoice = bil.invoice
    
WHERE bih.invoice_dt > '2019-12-29' OR bih.invoice_dt IS NULL

QUALIFY ROW_NUMBER() OVER (PARTITION BY bil.business_unit, bil.invoice, bil.line_seq_num ORDER BY bil.last_update_dttm DESC) = 1
