version: 2

sources:
  - name: name_source_ergbq
    project: | 
      {%- if target.name == "prd_target" -%} us-ergbq-prd-3693
      {%- elif target.name == "acc_target" -%} us-ergbq-qa-e523
      {%- else -%} rand-rusaweb
      {%- endif -%}
    schema: dataset_name_in_ergbq
    tables:
      - name: products
      - name: stores
      - name: sales_orders