{{ config(
    tags = ["ps_bi_hdr", "backoffice"], 
    schema = 'rlm_stg_tables_None', 
    alias = 'ps_bi_hdr'
    )
}}

SELECT
      business_unit
      ,invoice
      ,bill_to_cust_id
      ,bill_status
      ,contract_num
      ,invoice_type
      ,consol_hdr
      ,consol_key
      ,consol_setid
      ,consol_cust_id
      ,consol_bus_unit
      ,consol_invoice
      ,original_invoice
      ,prior_adj_invoice
      ,next_adj_invoice
      ,latest_invoice
      ,adjusted_flag
      ,bill_type_id
      ,bill_source_id
      ,bill_cycle_id
      ,bill_by_id
      ,hdr_fields_key
      ,billing_frequency
      ,template_ivc_flg
      ,template_invoice
      ,recurring_start_dt
      ,recurring_end_dt
      ,auto_gen_ivc_num
      ,from_dt
      ,to_dt
      ,address_seq_num
      ,bill_to_copies
      ,bill_to_media
      ,cntct_seq_num
      ,name1
      ,business_unit_to
      ,cr_card_flg
      ,subcust_qual1
      ,subcust_qual2
      ,bill_inquiry_phone
      ,billing_specialist
      ,billing_authority
      ,collector
      ,sales_person
      ,cr_analyst
      ,pymnt_terms_cd
      ,bank_cd
      ,bank_acct_key
      ,bi_currency_cd
      ,base_currency
      ,currency_cd_xeu
      ,final_curcnv_flg
      ,cur_rt_type
      ,cur_rt_source
      ,rate_mult
      ,rate_div
      ,rate_mult_xeu
      ,rate_div_xeu
      ,rate_mult_iu
      ,rate_div_iu
      ,rate_date
      ,bi_paid_at_src
      ,paid_amt
      ,forward_bal_amt
      ,invoice_amt_pretax
      ,invoice_amount
      ,paid_amt_bse
      ,forward_bal_bse
      ,invoice_pretax_bse
      ,invoice_amt_bse
      ,forward_bal_xeu
      ,invoice_pretax_xeu
      ,invoice_amt_xeu
      ,paid_amt_xeu
      ,invoice_dt
      ,accounting_dt
      ,dt_invoiced
      ,due_dt
      ,invoice_form_id
      ,ivc_printed_flg
      ,ivc_printed_dt
      ,edi_sent_flg
      ,cf_action_flg
      ,preload_ind
      ,entry_type
      ,entry_reason
      ,ar_lvl
      ,ar_dst_opt
      ,ar_entry_created
      ,gen_ar_item_flg
      ,business_unit_gl
      ,gl_lvl
      ,gl_entry_created
      ,enable_dfr_rev_flg
      ,dfr_acctg_dt_cd
      ,dfr_rev_proration
      ,dfr_mid_period_day
      ,dst_id_dfr
      ,bill_status_text
      ,manual_lin_num_flg
      ,last_line_seq_num
      ,last_line_aaux_seq
      ,last_note_seq_num
      ,accrue_unbilled
      ,doc_type
      ,doc_seq_nbr
      ,doc_seq_date
      ,pc_distrib_status
      ,po_ref
      ,business_unit_ca
      ,contract_dt
      ,contract_type
      ,direct_invoicing
      ,business_unit_om
      ,order_no
      ,rma_id
      ,order_date
      ,freight_terms
      ,bill_of_lading
      ,ship_to_cust_id
      ,ship_to_addr_num
      ,ship_id
      ,ship_type_id
      ,ship_from_bu
      ,sold_to_cust_id
      ,sold_to_addr_num
      ,activity_type
      ,system_source
      ,range_selection_id
      ,emplid
      ,ssn
      ,service_cust_id
      ,service_addr_num
      ,start_dt
      ,end_dt
      ,error_status_bi
      ,country_ship_to
      ,country_ship_from
      ,gen_ap_vchr_flg
      ,ap_created_dt
      ,doc_seq_status
      ,early_py_dscnt_pct
      ,ds_py_trms_time_id
      ,vat_entity
      ,max_tax_flg
      ,tot_su_tax
      ,tot_su_tax_bse
      ,tot_su_tax_xeu
      ,tot_vat
      ,tot_vat_bse
      ,tot_vat_xeu
      ,tot_vat_basis
      ,tot_vat_basis_bse
      ,tot_vat_basis_xeu
      ,payment_method
      ,packslip_no
      ,lc_id
      ,loc_doc_id
      ,paid_reference
      ,pprc_promo_cd
      ,emailid
      ,fax
      ,language_cd
      ,entry_event
      ,reimb_agreement
      ,bi_bu_tax_ind
      ,exd_invoice_no
      ,stx_tax_auth_cd
      ,tot_exd_amt
      ,tot_exd_amt_bse
      ,tot_stx_amt
      ,tot_stx_amt_bse
      ,physical_nature
      ,vat_treatment_grp
      ,country_vat_billfr
      ,country_vat_billto
      ,state_ship_to
      ,state_ship_from
      ,reprint_group_id
      ,mast_contr_id
      ,business_unit_am
      ,so_id
      ,business_unit_rf
      ,source_ref_type
      ,source_ref_no
      ,source_ref_key
      ,acceptgiro_ind
      ,ag_ref_nbr
      ,ivc_delivered_flg
      ,ivc_delivered_dt
      ,summarize_ivc_flg
      ,business_unit_pc
      ,project_id
      ,activity_id
      ,resource_type
      ,resource_category
      ,resource_sub_cat
      ,analysis_type
      ,att_ivc_img_flg
      ,user_amt1
      ,user_amt2
      ,user_amt1_bse
      ,user_amt2_bse
      ,user_amt1_xeu
      ,user_amt2_xeu
      ,user_dt1
      ,user_dt2
      ,user1
      ,user2
      ,user3
      ,user4
      ,user5
      ,user6
      ,user7
      ,user8
      ,user9
      ,process_instance
      ,add_dttm
      ,last_update_dttm
      ,last_maint_oprid
      ,bill_fss_status
      ,ofac_status
      ,sdn_publish_date
      ,fss_activity_dt
      ,fss_clear_oprid
      ,fss_user_ovr
      ,reason_cd
      ,reason_type
      ,public_voucher_nbr
      ,pvn_gen_lvl
      ,contract_line_num
      ,final_ff_ext_ind
      ,target_pymt_dt
      ,hold_until_dt
      ,bi_approval_status
      ,tot_vat_rvc
      ,tot_vat_rvc_bse
      ,tot_vat_rvc_xeu
      ,createoprid
      ,bi_create_proc
      ,bi_ap_lvl
      ,insert_datetime as source_insert_datetime

FROM {{ source( 'datalake-frontoffice-fs_bo', 'PS_BI_HDR') }} 
