{{ config(
    tags = ["ps_bi_hdr_line"], 
    alias = "ps_bi_hdr_line"
    )
}}

SELECT
        bih.business_unit
        ,bih.invoice
        ,bih.bill_to_cust_id
        ,bih.bill_status
        ,bil.contract_num
        ,bih.invoice_type
        ,bih.consol_hdr
        ,bih.consol_key
        ,bih.consol_setid
        ,bih.consol_cust_id
        ,bih.consol_bus_unit
        ,bih.consol_invoice
        ,bih.original_invoice
        ,bih.prior_adj_invoice
        ,bih.next_adj_invoice
        ,bih.latest_invoice
        ,bih.adjusted_flag
        ,bih.bill_type_id
        ,bih.bill_source_id
        ,bih.bill_cycle_id
        ,bih.bill_by_id
        ,bih.hdr_fields_key
        ,bih.billing_frequency
        ,bih.template_ivc_flg
        ,bih.template_invoice
        ,bih.recurring_start_dt
        ,bih.recurring_end_dt
        ,bih.auto_gen_ivc_num
        ,bih.from_dt
        ,bih.to_dt
        ,bih.address_seq_num
        ,bih.bill_to_copies
        ,bih.bill_to_media
        ,bih.cntct_seq_num
        ,bih.name1
        ,bih.business_unit_to
        ,bih.cr_card_flg
        ,bil.subcust_qual1
        ,bih.subcust_qual2
        ,bih.bill_inquiry_phone
        ,bih.billing_specialist
        ,bih.billing_authority
        ,bih.collector
        ,bih.sales_person
        ,bih.cr_analyst
        ,bih.pymnt_terms_cd
        ,bih.bank_cd
        ,bih.bank_acct_key
        ,bih.bi_currency_cd
        ,bih.base_currency
        ,bih.currency_cd_xeu
        ,bih.final_curcnv_flg
        ,bih.cur_rt_type
        ,bih.cur_rt_source
        ,bih.rate_mult
        ,bih.rate_div
        ,bih.rate_mult_xeu
        ,bih.rate_div_xeu
        ,bih.rate_mult_iu
        ,bih.rate_div_iu
        ,bih.rate_date
        ,bih.bi_paid_at_src
        ,bih.paid_amt
        ,bih.forward_bal_amt
        ,bih.invoice_amt_pretax
        ,bih.invoice_amount
        ,bih.paid_amt_bse
        ,bih.forward_bal_bse
        ,bih.invoice_pretax_bse
        ,bih.invoice_amt_bse
        ,bih.forward_bal_xeu
        ,bih.invoice_pretax_xeu
        ,bih.invoice_amt_xeu
        ,bih.paid_amt_xeu
        ,bih.invoice_dt
        ,bih.accounting_dt
        ,bih.dt_invoiced
        ,bih.due_dt
        ,bih.invoice_form_id
        ,bih.ivc_printed_flg
        ,bih.ivc_printed_dt
        ,bih.edi_sent_flg
        ,bih.cf_action_flg
        ,bih.preload_ind
        ,bih.entry_type
        ,bih.entry_reason
        ,bih.ar_lvl
        ,bih.ar_dst_opt
        ,bih.ar_entry_created
        ,bih.gen_ar_item_flg
        ,bih.business_unit_gl
        ,bih.gl_lvl
        ,bih.gl_entry_created
        ,bih.enable_dfr_rev_flg
        ,bih.dfr_acctg_dt_cd
        ,bih.dfr_rev_proration
        ,bih.dfr_mid_period_day
        ,bih.dst_id_dfr
        ,bih.bill_status_text
        ,bih.manual_lin_num_flg
        ,bih.last_line_seq_num
        ,bih.last_line_aaux_seq
        ,bih.last_note_seq_num
        ,bih.accrue_unbilled
        ,bih.doc_type
        ,bih.doc_seq_nbr
        ,bih.doc_seq_date
        ,bih.pc_distrib_status
        ,bil.po_ref
        ,bih.business_unit_ca
        ,bih.contract_dt
        ,bih.contract_type
        ,bih.direct_invoicing
        ,bih.business_unit_om
        ,bih.order_no
        ,bil.rma_id
        ,bih.order_date
        ,bih.freight_terms
        ,bih.bill_of_lading
        ,bih.ship_to_cust_id
        ,bih.ship_to_addr_num
        ,bih.ship_id
        ,bih.ship_type_id
        ,bih.ship_from_bu
        ,bih.sold_to_cust_id
        ,bih.sold_to_addr_num
        ,bih.activity_type
        ,bih.system_source
        ,bih.range_selection_id
        ,bil.emplid
        ,bih.ssn
        ,bih.service_cust_id
        ,bih.service_addr_num
        ,bih.start_dt
        ,bih.end_dt
        ,bih.error_status_bi
        ,bih.country_ship_to
        ,bih.country_ship_from
        ,bih.gen_ap_vchr_flg
        ,bih.ap_created_dt
        ,bih.doc_seq_status
        ,bih.early_py_dscnt_pct
        ,bih.ds_py_trms_time_id
        ,bih.vat_entity
        ,bih.max_tax_flg
        ,bih.tot_su_tax
        ,bih.tot_su_tax_bse
        ,bih.tot_su_tax_xeu
        ,bih.tot_vat
        ,bih.tot_vat_bse
        ,bih.tot_vat_xeu
        ,bih.tot_vat_basis
        ,bih.tot_vat_basis_bse
        ,bih.tot_vat_basis_xeu
        ,bih.payment_method
        ,bih.packslip_no
        ,bih.lc_id
        ,bih.loc_doc_id
        ,bih.paid_reference
        ,bih.pprc_promo_cd
        ,bih.emailid
        ,bih.fax
        ,bih.language_cd
        ,bih.entry_event
        ,bih.reimb_agreement
        ,bih.bi_bu_tax_ind
        ,bih.exd_invoice_no
        ,bih.stx_tax_auth_cd
        ,bih.tot_exd_amt
        ,bih.tot_exd_amt_bse
        ,bih.tot_stx_amt
        ,bih.tot_stx_amt_bse
        ,bih.physical_nature
        ,bih.vat_treatment_grp
        ,bih.country_vat_billfr
        ,bih.country_vat_billto
        ,bih.state_ship_to
        ,bih.state_ship_from
        ,bih.reprint_group_id
        ,bih.mast_contr_id
        ,bih.business_unit_am
        ,bih.so_id
        ,bih.business_unit_rf
        ,bih.source_ref_type
        ,bih.source_ref_no
        ,bih.source_ref_key
        ,bih.acceptgiro_ind
        ,bih.ag_ref_nbr
        ,bih.ivc_delivered_flg
        ,bih.ivc_delivered_dt
        ,bih.summarize_ivc_flg
        ,bil.business_unit_pc
        ,bil.project_id
        ,bil.activity_id
        ,bih.resource_type
        ,bih.resource_category
        ,bil.resource_sub_cat
        ,bih.analysis_type
        ,bih.att_ivc_img_flg
        ,bil.user_amt1
        ,bil.user_amt2
        ,bil.user_amt1_bse
        ,bil.user_amt2_bse
        ,bil.user_amt1_xeu
        ,bil.user_amt2_xeu
        ,bil.user_dt1
        ,bil.user_dt2
        ,bil.user1
        ,bil.user2
        ,bil.user3
        ,bil.user4
        ,bil.user5
        ,bil.user6
        ,bil.user7
        ,bil.user8
        ,bil.user9
        ,bih.process_instance
        ,bil.add_dttm
        ,bih.last_update_dttm
        ,bih.last_maint_oprid
        ,bih.bill_fss_status
        ,bih.ofac_status
        ,bih.sdn_publish_date
        ,bih.fss_activity_dt
        ,bih.fss_clear_oprid
        ,bih.fss_user_ovr
        ,bih.reason_cd
        ,bih.reason_type
        ,bih.public_voucher_nbr
        ,bih.pvn_gen_lvl
        ,bih.contract_line_num
        ,bih.final_ff_ext_ind
        ,bih.target_pymt_dt
        ,bih.hold_until_dt
        ,bih.bi_approval_status
        ,bih.tot_vat_rvc
        ,bih.tot_vat_rvc_bse
        ,bih.tot_vat_rvc_xeu
        ,bih.createoprid
        ,bih.bi_create_proc
        ,bih.bi_ap_lvl
        ,bil.line_seq_num
        ,bil.invoice_line
        ,bil.original_line_seq
        ,bil.next_adj_line_seq
        ,bil.prior_adj_line_seq
        ,bil.latest_line_seq
        ,bil.adj_line_type
        ,bil.line_type
        ,bil.rt_effdt
        ,bil.charge_from_dt
        ,bil.charge_to_dt
        ,bil.identifier
        ,bil.descr
        ,bil.unit_of_measure
        ,bil.qty
        ,bil.orig_qty
        ,bil.unit_amt
        ,bil.price_recalc_flg
        ,bil.tax_cd
        ,bil.tax_exempt_cert
        ,bil.tax_exempt_flg
        ,bil.gross_extended_amt
        ,bil.net_extended_amt
        ,bil.orig_amount
        ,bil.gross_extended_bse
        ,bil.net_extended_bse
        ,bil.gross_extended_xeu
        ,bil.net_extended_xeu
        ,bil.tax_amt
        ,bil.tax_amt_bse
        ,bil.tax_amt_xeu
        ,bil.tax_pct
        ,bil.final_tax_flg
        ,bil.bi_tax_timing
        ,bil.vat_basis_amt
        ,bil.vat_basis_amt_bse
        ,bil.vat_basis_amt_xeu
        ,bil.vat_amt
        ,bil.vat_amt_bse
        ,bil.vat_amt_xeu
        ,bil.vat_trans_amt
        ,bil.vat_trans_amt_bse
        ,bil.vat_txn_type_cd
        ,bil.tax_cd_vat
        ,bil.tax_cd_vat_pct
        ,bil.vat_applicability
        ,bil.prod_grp_setid
        ,bil.vat_product_group
        ,bil.product_kit_id
        ,bil.vat_distrib_status
        ,bil.tax_vat_flg
        ,bil.rev_recog_basis
        ,bil.deferred_status
        ,bil.accrue_dt
        ,bil.tot_line_dst_pct
        ,bil.tot_line_dfr_pct
        ,bil.tot_line_uar_pct
        ,bil.tot_line_dst_amt
        ,bil.tot_line_dfr_amt
        ,bil.tot_line_uar_amt
        ,bil.tot_line_dst_bse
        ,bil.tot_line_dfr_bse
        ,bil.tot_line_uar_bse
        ,bil.tot_line_dst_xeu
        ,bil.tot_line_dfr_xeu
        ,bil.tot_line_uar_xeu
        ,bil.tot_discount_amt
        ,bil.tot_surcharge_amt
        ,bil.tot_discount_bse
        ,bil.tot_surcharge_bse
        ,bil.tot_discount_xeu
        ,bil.tot_surcharge_xeu
        ,bil.line_dst_seq_num
        ,bil.line_dfr_seq_num
        ,bil.line_uar_seq_num
        ,bil.po_line
        ,bil.bill_plan_id
        ,bil.bplan_ln_nbr
        ,bil.event_occurrence
        ,bil.xref_seq_num
        ,bil.contract_ppd_seq
        ,bil.order_int_line_no
        ,bil.sched_line_nbr
        ,bil.business_unit_rma
        ,bil.rma_line_nbr
        ,bil.product_id
        ,bil.dist_cfg_flag
        ,bil.ship_date
        ,bil.ship_time
        ,bil.sequence_nbr
        ,bil.resource_id
        ,bil.empl_rcd
        ,bil.accumulate
        ,bil.ist_txn_flg
        ,bil.ist_distrib_status
        ,bil.inventory_item
        ,bil.fiscal_regime
        ,bil.nature_of_txn1
        ,bil.nature_of_txn2
        ,bil.identifier_tbl
        ,bil.defer_dt
        ,bil.merch_type
        ,bil.list_price
        ,bil.vat_treatment
        ,bil.vat_svc_supply_flg
        ,bil.vat_service_type
        ,bil.vat_dst_acct_type
        ,bil.vat_advpay_flg
        ,bil.voucher_style
        ,bil.country_loc_buyer
        ,bil.state_loc_buyer
        ,bil.country_loc_seller
        ,bil.state_loc_seller
        ,bil.country_vat_supply
        ,bil.state_vat_supply
        ,bil.country_vat_perfrm
        ,bil.state_vat_perfrm
        ,bil.exd_cust_catg_cd
        ,bil.stx_cust_catg_cd
        ,bil.vat_dflt_done_flg
        ,bil.inv_item_id
        ,bil.qty_base
        ,bil.exd_invoice_line
        ,bil.org_setid
        ,bil.org_code
        ,bil.org_tax_loc_cd
        ,bil.exd_appl_flg
        ,bil.stx_appl_flg
        ,bil.exs_dflts_applied
        ,bil.exs_tax_txn_type
        ,bil.exd_itm_catg_cd
        ,bil.stx_itm_catg_cd
        ,bil.exs_serv_tax_flg
        ,bil.stx_form_cd
        ,bil.form_distrib_stat
        ,bil.exd_assess_value
        ,bil.exd_uom
        ,bil.exd_conversion_rt
        ,bil.exd_use_av_flg
        ,bil.exd_tax_rate_cd
        ,bil.exd_tax_rate_src
        ,bil.exd_tax_amt
        ,bil.exd_tax_amt_bse
        ,bil.exd_tax_amt_rpt
        ,bil.stx_tax_rate_cd
        ,bil.stx_tax_rate_src
        ,bil.stx_tax_amt
        ,bil.stx_tax_amt_bse
        ,bil.stx_tax_amt_rpt
        ,bil.exs_currency_rptg
        ,bil.business_unit_amto
        ,bil.asset_id
        ,bil.profile_id
        ,bil.cost_type
        ,bil.state_vat_default
        ,bil.lang_descr_ovr
        ,bil.ca_pgp_seq
        ,bil.sum_template_id
        ,bil.sum_group_type
        ,bil.sum_group_id
        ,bil.cust_deposit_id
        ,bil.customer_po_line
        ,bil.customer_po_sched
        ,bil.pc_cf_change_flg
        ,bil.credit_reason
        ,bil.vat_rvrse_chg_gds
        ,bil.tax_cd_vat_rvc
        ,bil.tax_cd_vat_rvc_pct
        ,bil.vat_amt_rvc
        ,bil.vat_amt_rvc_bse
        ,bil.vat_amt_rvc_xeu
        ,bil.temp_invoice
        ,bil.source_insert_datetime

FROM {{ ref( 'stg_ps_bi_hdr')}} as bih

INNER JOIN {{ ref( 'stg_ps_bi_line')}} as bil
    ON bih.business_unit = bil.business_unit 
    AND bih.invoice = bil.invoice
    
WHERE bih.invoice_dt > '2019-12-29' OR bih.invoice_dt IS NULL
