{{ config(
    tags = ["ps_customer", "dedup", "backoffice"], 
    alias = 'ps_customer'
    )
}}

SELECT
        setid
        ,cust_id
        ,name1
        ,cntct_seq_num
        ,cust_status
        ,cust_status_dt
        ,stcust_days
        ,expiration_date
        ,exp_pending
        ,template_addr
        ,customer_type
        ,since_dt
        ,add_dt
        ,nameshort
        ,name2
        ,name3
        ,name1_ac
        ,name2_ac
        ,name3_ac
        ,address_seq_num
        ,corporate_setid
        ,corporate_cust_id
        ,parent_setid
        ,parent_cust_id
        ,remit_from_setid
        ,remit_from_cust_id
        ,crspd_setid
        ,crspd_cust_id
        ,consol_bus_unit
        ,vendor_setid
        ,vendor_id
        ,refer_to_setid
        ,refer_to_cust_id
        ,review_days
        ,former_name_1
        ,former_name_2
        ,subcust_use
        ,subcust_qual1
        ,subcust_qual2
        ,cur_rt_type
        ,currency_cd
        ,ship_to_flg
        ,bill_to_flg
        ,sold_to_flg
        ,broker_flg
        ,indirect_cust_flg
        ,cust_level
        ,address_seq_sold
        ,cntct_seq_sold
        ,address_seq_ship
        ,cntct_seq_ship
        ,address_seq_brk
        ,address_seq_ind
        ,hold_update_sw
        ,roleuser
        ,taxpayer_id
        ,web_url
        ,stock_symbol
        ,reports_to_sponsor
        ,spnsr_level
        ,spnsr_type
        ,spnsr_program
        ,cost_liv_incr_pct
        ,cfda_nbr
        ,allow_copi
        ,multi_pi
        ,foreign_flag
        ,fed_sp_type
        ,ofac_status
        ,reason_cd
        ,fss_offset_days
        ,gm_federal_flag
        ,us_flag_carrier
        ,loc_indicator
        ,gm_loc_sponsor_id
        ,ggov_flg
        ,fa_spnsr_base_id
        ,gm_del_loc_refs_sw
        ,grants_sponsor_flg
        ,spnsr_salary_cap
        ,federal_indicator
        ,trading_partner
        ,ipac_interface
        ,cntct_seq_ipac
        ,customer_alc
        ,customer_do
        ,symbol_req
        ,source_system
        ,cust_usf_status
        ,emplid
        ,fed_share_pct
        ,cont_allow_pct
        ,cont_no_allw_pct
        ,cust_field_c1_a
        ,cust_field_c1_b
        ,cust_field_c1_c
        ,cust_field_c1_d
        ,cust_field_c2
        ,cust_field_c4
        ,cust_field_c6
        ,cust_field_c8
        ,cust_field_c10_a
        ,cust_field_c10_b
        ,cust_field_c10_c
        ,cust_field_c10_d
        ,cust_field_c30_a
        ,cust_field_c30_b
        ,cust_field_c30_c
        ,cust_field_c30_d
        ,cust_field_n12_a
        ,cust_field_n12_b
        ,cust_field_n12_c
        ,cust_field_n12_d
        ,cust_field_n15_a
        ,cust_field_n15_b
        ,cust_field_n15_c
        ,cust_field_n15_d
        ,last_maint_oprid
        ,date_last_maint
        ,rna_billing_method
        ,rna_time_entry_mhd
        ,rna_source_system
        ,deptid
        ,lastupddttm
        ,insert_datetime as source_insert_datetime

    from {{ source( 'datalake-frontoffice-fs_bo', 'PS_CUSTOMER') }} 
    
QUALIFY ROW_NUMBER() OVER (PARTITION BY  cust_id, setid ORDER BY lastupddttm DESC) = 1
